### ISSUE TITLE
??? RBK0090E: Option -E requires a parameter.

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-LoxberryBackup#15]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/122935-plugin-loxberry-backup?p=147814#post147814

```
OK: Starting backup
??? RBK0090E: Option -E requires a parameter.
ERROR: Backup failed with error code 107
```
Irgendwas stimmt mit meinen übergebenen E-Mail Parametern nicht.

**Comment by framps** [comment]
Sorry: Ohne Log ist es mir nicht moeglich zu helfen. Bitte raspiBackup mit der zusaetzlichen Option   `-l debug` zum Erzeugen von dem debuglog raspiBackup.log noch einmal aufrufen. Eventuell die Option `-L` benutzen um das Ziel des Logs zu definieren.

**Comment by christianTF** [comment]
Kein Problem, muss mir das selbst erst ansehen.
Ich hab bei meinem Aufruf mal was geändert, und glaube, dass ich seitdem meine Parameter falsch zusammensetze.
Also sicher kein Problem auf deiner Seite! :-)

**Comment by framps** [comment]
Das wuerde ich so nicht unterschreiben. Du weisst doch: Nobody ist perfect :laughing: Aber im Log wuerde ich schnell sehen welche Parameter genau uebergeben werden. Das hilft Dir sicherlich auch da mal reinzusehen. Gleich am Anfang werden alle Optionen und Parameter gelogged.
