### ISSUE TITLE
Errror when review logfiles

### ISSUE THREAD

**Issue by Woersty** [christianTF/LoxBerry-Plugin-LoxberryBackup#17]
Wenn ich http://loxberrydev/admin/plugins/lbbackup/?form=logfiles aufrufe sehe ich nur das Loxberry Error-Logo?

Habe das PreRelease 1.0.4 ...

**Comment by christianTF** [comment]
Stimmt, ist mir auch aufgefallen, ich dachte, ich hätte nur bei mir was geschreddert.

**Comment by christianTF** [comment]
Problem ist durch falschen LBBackup-Code (serverseitiger Abruf statt von `http://localhost` von `http:// . lbhostname()` im Zusammenspiel mit der Änderung der /etc/hosts.

Vor 1.2.5 wurde der Hostname mit localhost aufgelöst, dort benötigt es keine Authentifizierung.
Seit 1.2.5 wird die richtige IP zurückgeliefert und deswegen Access Denied

Ist im master schon seit längerem umgebaut auf die Verwendung von LoxBerry::Web::loglist_html, deswegen ist es mir am DEV nie aufgefallen, sondern erst auf einem Produktiv-Pi.

Ich mach gleich 1.0.5
