### ISSUE TITLE
Fehlermeldung printf

### ISSUE THREAD

**Issue by Woersty** [christianTF/LoxBerry-Plugin-LoxberryBackup#18]
```
!!! RBK0157W: No services to stop. 
/usr/local/bin/raspiBackup.sh: line 938: printf: --: invalid option 
printf: usage: printf [-v var] format [arguments] 
--- RBK1005I: Copy %1 to %2 
```

**Comment by christianTF** [comment]
Nicht (mehr) reproduzierbar.

**Comment by christianTF** [comment]
Gerade in einem Log eines anderen Benutzers von Juli 2019 im Forum gesehen

**Comment by framps** [comment]
Waere hilfreich bei der Problemursachenforschung wenn @Woersty und der andere Benutzer den genauen Codestand (git sha) von raspiBackup angeben kann. Diese wird in der Meldung RBK0009I ausgegeben.

Beispiel:
```
--- RBK0009I: obelix.framp.de: raspiBackup.sh V0.6.4.4-dev (a0940d3) started at Wed Nov 13 22:59:43 CET 2019.
```

**Comment by christianTF** [comment]
Hi framp,

Ist schon gefixt: https://github.com/christianTF/LoxBerry-Plugin-LoxberryBackup/commit/61c46759944f9586ce9d7179136dc85027f1dc08

Ich hab die Extensions lokal mitgeliefert, und die waren noch nicht mit %s, sondern noch die alten.
