### ISSUE TITLE
LoxBerry Backup finished with error

### ISSUE THREAD

**Issue by di3t0** [christianTF/LoxBerry-Plugin-LoxberryBackup#19]
Ich bekomme diese Fehlermeldung:

LoxBerry Backup finished with error. See the logfile for details.
Backup started at 08.03.2019 15:00:02 and finished at 08.03.2019 15:11:05
Disk space info on /backup
192.168.100.222:/volume1/Loxberry (/backup) | Size: 2.68 TB | Used: 675.25 GB | Free: 2.02 TB

Wenn ich den Log aufmache:

Die Log-Datei existiert nicht. Es kann sein, dass das entsprechende Plugin noch nichts sendet oder fehlerhaft ist. Lade die Seite erneut und versuche es noch einmal.

Fehlermeldung 109,habe ich einmal im Log gesehen.

Was damit?

**Comment by christianTF** [comment]
Wenn du rebootest, passiert das weiterhin?

Dass kein Log erzeugt wird, ist an sich ein Indikator für eine volle RAM-Disk.

**Comment by christianTF** [comment]
Geschlossen wegen Inaktivität
