### ISSUE TITLE
Automatisch Zippen in der raspiConfig standardmäßig aktiv

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-LoxberryBackup#2]
Das sed im daemon scheint nicht richtig den Parameter DEFAULT_ZIP_BACKUP auf 0 zu setzen.
Deswegen erscheint beim Backup der Fehler, dass der Typ DDZ nicht mit Kompression geht (Parameter nicht gültig).
Das wird im Daemon ausgeführt.

sed -i.bak 's/^\(DEFAULT_ZIP_BACKUP=\).*/\1"0"/' /usr/local/etc/raspiBackup.conf

Evt. vor jedem Backup ausführen.

**Comment by christianTF** [comment]
Neue Parameter von raspiBackup verwenden

**Comment by framps** [comment]
`sed -i.bak -r 's/^(DEFAULT_ZIP_BACKUP=)./\10/' /usr/local/etc/raspiBackup.conf` sollte funktionieren oder Aufrufoption -z+ dann mit der nächsten Version 0.6.3.2 :smiley:
