### ISSUE TITLE
Wäre "freier Platz" nicht sinnvoller als "Größe"?

### ISSUE THREAD

**Issue by Woersty** [christianTF/LoxBerry-Plugin-LoxberryBackup#35]
```
Filesystem                  Size  Used Avail Use% Mounted on
//192.168.115.252/Loxberry   25T   21T  4.2T  84% /media/smb/192.168.115.252/Loxberry
```
![image](https://user-images.githubusercontent.com/20454116/115380898-54559b80-a1d3-11eb-87cd-4d4f1cbaefd0.png)

**Comment by christianTF** [comment]
Kommt von LB-Core. 
Ist ein generisches Control, es soll helfen, den richtigen Datenträger zu identifizieren.
