### ISSUE TITLE
mkdir: cannot create directory '/backup': Permission denied

### ISSUE THREAD

**Issue by topoff82** [christianTF/LoxBerry-Plugin-LoxberryBackup#4]
Hi there.
Installed the Plugin via Loxberry installer - install was OK - Loxberry Interface is also fine had only the issue that the installer had no permission to create the folder /backup.

I can do this myself no problem - the only question I have is where to create this directory - top level of loxberry or of root user raspberry? or somewhere else?

Would be happy to get an answer!
Tom

**Comment by christianTF** [comment]
Hi Tom,
thanks for your feedback!

You're right, the installer has no permissions to create the /backup dir.

The real installation of Framps raspiBackup happens after the reboot with root permissions. This should (as far as I can remember) also create the backup directory.

The default configuration is to do the backups in /backup. 
/backup should be mounted to your external backup storage, therefore an external disk or a CIFS or NFS share. 
Mounting such external storage is not a functionality, neither from the plugin nor from raspiBackup. There are to many possibilities, and you should stick that config manually to your fstab (or autofs).

If you want to change the backup destination, you can do so in the `/usr/local/etc/raspiBackup.conf` file - this should work, but I've never tested that. 

Framp has added a functionality by my request, to additionally backup the fstab file. That makes it easier to recover a fileshare or mount in the case of a recovery. Check the backup folders if you can find that file.

I plan to add some notification features to the plugin, but I'm waiting for the release of the new LoxBerry version, as it brings some notification features with it. If you have configured your mail account in LoxBerry, you already should get email notifications from backups.

Best regards,
Christian

**Comment by topoff82** [comment]
Thank you!
Worked without any problem - created /backup manually with mk /backup -> mounted -> backup running fine
Tom
