### ISSUE TITLE
LogFile

### ISSUE THREAD

**Issue by loxatsonnenberg** [christianTF/LoxBerry-Plugin-LoxberryBackup#5]
Hello Christian,
can you please have a look at my logfile, why is the backup-dir deleted immediatly?
Fake mode is not checked. Backup-dir was manually created but currently no network drive is mounted.

--- RBK0031I: Checking whether new version is available.
20180125-224409: MSG     --- RBK0031I: Checking whether new version is available.
--- RBK0168I: raspiBackup.sh beta version 0.6.3.2 is available. Any help to test this beta is appreciated.
20180125-224411: MSG           --- RBK0168I: raspiBackup.sh beta version 0.6.3.2 is available. Any help to test this beta is appreciated.
??? RBK0027E: No external device mounted on /backup. SD card would be used for backup.
20180125-224415: MSG        ??? RBK0027E: No external device mounted on /backup. SD card would be used for backup.
Invocation parms: ' -o : -a : -k 6 -t ddz -L current /backup'
--- RBK0105I: Deleting new backup directory /backup/loxberry/loxberry-ddz-backup-20180125-224408.
20180125-224415: MSG                 --- RBK0105I: Deleting new backup directory /backup/loxberry/loxberry-ddz-backup-20180125-224408.
??? RBK0005E: Backup failed. Check previous error messages for details.
20180125-224415: MSG                 ??? RBK0005E: Backup failed. Check previous error messages for details.

**Comment by framps** [comment]
You didn't mount an external partition on /backup. That's a check executed by raspiBackup because it doesn't make sense to save the backup on the SD card itself :wink:

**Comment by christianTF** [comment]
Yes, that's it!
See the documentation at http://www.loxwiki.eu/display/LOXBERRY/Loxberry+Backup

 ##  Backup-Ziel einrichten
Das Plugin schreibt alle Backups an den Ordner /backup (bzw. dessen Unterordner). Eine Änderung ist derzeit nicht möglich.

In das backup-Verzeichnis muss entweder ein externer Datenträger, oder ein Netzlaufwerk eingebunden werden. Diese Einbindung muss manuell erfolgen.  Siehe dazu einschlägige Dokumentation zum Mounten in der Datei /etc/fstab.

**Wurde kein externes Medium in /backup eingebunden, erkennt das die Backup-Routine und bricht ab** (es wird also nicht unerwartet die SD-Karte des Loxberrys vollgeschrieben).

btw, hi @framps :smiley:

**Comment by loxatsonnenberg** [comment]
Ok, thanks.
dann mache ich das geschwind. Hatte dies so interpretiert, dass dies im Fake-Mode auch keine Rolle spielt.
