### ISSUE TITLE
Installation raspiBackup hängt/bricht ab

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-LoxberryBackup#6]
```
--- RBI0001I: raspiBackupInstall.sh 0.3.6, 2017-09-05/19:55:44 - af47c86
--- RBI0032I: Checking if there is a beta version available.
--- RBI0033I: Beta version 0.6.3.2 is available.
/opt/loxberry/data/plugins/lbbackup/raspiBackupInstall.sh: line 796: MSG_ANSWER_CHARS_ye: unbound variable
/opt/loxberry/data/plugins/lbbackup/raspiBackupInstall.sh: line 466: $3: unbound variable

```

Die Meldung kommt auch beim manuellen Versuch.

https://github.com/christianTF/LoxBerry-Plugin-LoxberryBackup/blob/f3f89ba0890870336eba1cd61f147aedd46bbb34/data/raspiBackupInstall.sh#L796

--> Neue Version von raspiBackup einsetzen, ggf. manuell installieren

**Comment by christianTF** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/122935-plugin-loxberry-backup?p=144136#post144136

**Comment by framps** [comment]
Das ist ein Typo im Code und seitdem die neue Beta online ist wird dieser Fehler leider sichtbar. Ich habe es eben gefixed. Einfach noch mal den aktuellen Installer downloaded. Sorry for the inconvenience.

**Comment by christianTF** [comment]
Closed mit https://github.com/christianTF/LoxBerry-Plugin-LoxberryBackup/commit/2878bc1b28a86ab87115b4b4fde6801be5ab1ffc
